// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MGPC.Game.EditorPart.Generated;
//
//    var scenario = Scenario.FromJson(jsonString);

namespace MGPC.Game.EditorPart.Generated
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Scenario
    {
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("waves")]
        public List<Wave> Waves { get; set; }
    }

    public partial class Wave
    {
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("activatedAt")]
        public double ActivatedAt { get; set; }

        [JsonProperty("duration")]
        public long Duration { get; set; }

        [JsonProperty("pathGroups")]
        public List<PathGroup> PathGroups { get; set; }
    }

    public partial class PathGroup
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("activatedAt")]
        public long ActivatedAt { get; set; }

        [JsonProperty("paths")]
        public List<Path> Paths { get; set; }
    }

    public partial class Path
    {
        [JsonProperty("id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("templateId")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long TemplateId { get; set; }
    }

    public partial class Scenario
    {
        public static Scenario FromJson(string json) => JsonConvert.DeserializeObject<Scenario>(json, MGPC.Game.EditorPart.Generated.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Scenario self) => JsonConvert.SerializeObject(self, MGPC.Game.EditorPart.Generated.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
