// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using F3Fes2021.Game.Extension.MG.Fishing.Creature.EditorPart.Generated;
//
//    var creature = Creature.FromJson(jsonString);

namespace MGPC.Tool.Extension.HThN6Y.Design.Creature.EditorPart.Generated
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Creature
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("kind")]
        public string Kind { get; set; }

        [JsonProperty("artAssetName")]
        public string ArtAssetName { get; set; }

        [JsonProperty("scaleSize")]
        public float ScaleSize { get; set; }

        [JsonProperty("avatarPosition")]
        public string AvatarPosition { get; set; }

        [JsonProperty("colliderCenter")]
        public string ColliderCenter { get; set; }

        [JsonProperty("colliderSize")]
        public string ColliderSize { get; set; }
    }

    public partial class Creature
    {
        public static Creature FromJson(string json) => JsonConvert.DeserializeObject<Creature>(json, MGPC.Tool.Extension.HThN6Y.Design.Creature.EditorPart.Generated.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Creature self) => JsonConvert.SerializeObject(self, MGPC.Tool.Extension.HThN6Y.Design.Creature.EditorPart.Generated.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
