// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using F3Fes2021.Game.Extension.MG.Fishing.Projectile.EditorPart.Generated;
//
//    var projectile = Projectile.FromJson(jsonString);

namespace MGPC.Tool.Extension.HThN6Y.Design.Projectile.EditorPart.Generated
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Projectile
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("speed")]
        public long Speed { get; set; }

        [JsonProperty("duration")]
        public long Duration { get; set; }

        [JsonProperty("artAssetName")]
        public string ArtAssetName { get; set; }

        [JsonProperty("colliderSize")]
        public string ColliderSize { get; set; }
    }

    public partial class Projectile
    {
        public static Projectile FromJson(string json) => JsonConvert.DeserializeObject<Projectile>(json, MGPC.Tool.Extension.HThN6Y.Design.Projectile.EditorPart.Generated.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Projectile self) => JsonConvert.SerializeObject(self, MGPC.Tool.Extension.HThN6Y.Design.Projectile.EditorPart.Generated.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
